// TermsConditions.tsx
import React from 'react';
import { Link } from 'react-router-dom';

const TermsConditions = () => {
  return (
    <div className="min-h-screen bg-gray-900 text-white/90 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto space-y-8">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-white mb-4">Terms of Use</h1>
          <nav className="space-x-4">
            <Link to="/privacy-policy" className="text-blue-400 hover:text-blue-300">Privacy Policy</Link>
            <Link to="/refund-policy" className="text-blue-400 hover:text-blue-300">Refund Policy</Link>
          </nav>
        </div>

        <div className="space-y-6">
          <section className="text-sm text-white/70">
            <p>Last Update: February 22, 2025</p>
            <p className="mt-4">
              THIS TERMS OF USE AGREEMENT (the "Agreement") constitutes a legally binding agreement between <span className="font-semibold">thumbnailslabs</span>, and the users of its AI text & image-generating tool (the "Tool"), regarding access to & use of the Tool and any other media form, channel, mobile website, or mobile application related, linked, or otherwise connected thereto. This Agreement sets forth the legally binding terms & conditions governing the users' ("Users") use of the Tool. Failure to agree with & adhere to all terms, conditions, & obligations herein will result in the immediate termination of the User's access to the Tool and the cessation of this Agreement.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-blue-400">1. Intellectual Property Rights</h2>
            <div className="mt-4 space-y-4">
              <p>
                Unless otherwise indicated, the Tool and all content generated by the Tool, including but not limited to texts, images, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music, artwork, and computer code (collectively, the "Content"), are owned, controlled, or licensed by <span className="font-semibold">thumbnailslabs</span>. The Content is protected by copyright, trademark, and other intellectual property rights and laws.
              </p>
              <p>
                Except as expressly provided in this Agreement, no part of the Tool and no Content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any commercial purpose whatsoever, without <span className="font-semibold">thumbnailslabs'</span> express prior written consent.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-blue-400">2. User Responsibility for Copyrighted Content</h2>
            <div className="mt-4 space-y-4">
              <p>
                When using the Tool to create projects or any content ("Projects"), Users must respect intellectual property rights and ensure all content, including images and characters, complies with legal requirements. Users are solely responsible for avoiding the unauthorized use of copyrighted materials, including but not limited to cartoon characters, celebrities, famous artwork, trademarked logos, or any proprietary content. <span className="font-semibold">thumbnailslabs</span> is not liable for the inclusion of such materials in Users' Projects. It is the User's responsibility to ensure they have the necessary rights or licenses for any third-party assets used. In case of legal issues arising from the use of copyrighted or proprietary materials, the User agrees to indemnify and hold harmless <span className="font-semibold">thumbnailslabs</span> against any claims, damages, expenses, or liabilities.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-blue-400">3. Ownership of Materials</h2>
            <div className="mt-4 space-y-4">
              <p>
                All original content created by the Tool at the behest of the User, including but not limited to customized images and graphics ("Projects"), shall be the exclusive property of the User. However, <span className="font-semibold">thumbnailslabs</span> retains a non-exclusive, transferable, sub-licensable, royalty-free, worldwide license to use such Projects for marketing, research, development, and other business purposes. This includes the right to modify, reproduce, distribute, display, and perform such Projects.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-blue-400">4. Third-Party Assets Responsibility</h2>
            <div className="mt-4 space-y-4">
              <p>
                In the event that any Project created using the Tool incorporates third-party assets that are not owned by <span className="font-semibold">thumbnailslabs</span>, such as fonts, images, or other materials necessitating a commercial license for legal use ("Third-Party Assets"), it is the sole responsibility of the User to ensure that they have obtained all necessary licenses and rights to use these Third-Party Assets. The User agrees to comply with any terms & conditions associated with these Third-Party Assets. <span className="font-semibold">thumbnailslabs</span> explicitly disclaims any responsibility or liability for the legal use of Third-Party Assets incorporated into the Projects by the User. In case of any legal issues or claims arising from the use of Third-Party Assets, the User agrees to indemnify and hold harmless <span className="font-semibold">thumbnailslabs</span> against any claims, damages, expenses, or liabilities.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-blue-400">5. User Representations</h2>
            <div className="mt-4 space-y-4">
              <p>
                By using the Tool, Users affirm that they have the legal capacity and authority to enter into this Agreement and to comply with all terms herein. Users represent that they are not minors in their jurisdiction of residence and will not access the Tool through any automated, non-human means, whether through a bot, script, or otherwise. Users further covenant that their use of the Tool will not involve any illegal or unauthorized purpose and will not violate any applicable law or regulation.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-blue-400">6. Prohibited Activities</h2>
            <div className="mt-4 space-y-4">
              <p>
                Users are strictly prohibited from using the Tool for any purpose other than as intended by <span className="font-semibold">thumbnailslabs</span>. The Tool shall not be used for any commercial endeavors unrelated to the services provided by <span className="font-semibold">thumbnailslabs</span>. Users agree to refrain from engaging in prohibited activities, which include but are not limited to:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Unauthorized access to the Tool</li>
                <li>Using the Tool to create or disseminate content that is illegal, offensive, racist, or controversial</li>
                <li>Data mining or scraping</li>
                <li>Interference with the Tool's security features</li>
                <li>Unauthorized linking or framing to the Tool</li>
                <li>Engaging in fraudulent or deceptive practices</li>
                <li>Disrupting the operations or network of <span className="font-semibold">thumbnailslabs</span></li>
                <li>Attempting to decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Tool</li>
                <li>Bypassing any measures <span className="font-semibold">thumbnailslabs</span> may use to prevent or restrict access to the Tool</li>
                <li>Harassing or threatening <span className="font-semibold">thumbnailslabs'</span> employees or agents</li>
                <li>Removing copyright notices from any content</li>
                <li>Uploading or transmitting viruses or other harmful, disruptive, or destructive files</li>
                <li>Engaging in any activity contrary to applicable laws & regulations</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-blue-400">7. User Feedback</h2>
            <div className="mt-4 space-y-4">
              <p>
                Any and all feedback, comments, suggestions, ideas, enhancement requests, recommendations, or other information provided by Users in connection with the Tool ("Feedback") shall be solely owned by <span className="font-semibold">thumbnailslabs</span>. Users hereby assign to <span className="font-semibold">thumbnailslabs</span> all rights in the Feedback.
              </p>
            </div>
          </section>
        </div>

        <footer className="text-center text-white/60 pt-8">
          <p>Last updated: February 22, 2025</p>
          <p>Contact: support@thumbnailslabs.com</p>
        </footer>
      </div>
    </div>
  );
};

export default TermsConditions;